#!/bin/bash

find . -depth -exec bash -c '
  for file; do
    tail=${file##*/}
    alnum_only=${tail//[^[:alnum:]. _-]/_}
    mv -v "$file" "${file%/*}/$alnum_only"
  done
' sh {} + | tee renamed_files.txt

